In [60]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [61]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

In [62]:
dataset = pd.read_csv("/content/drive/My Drive/AI_ASSIGNMENT/roo_data (1).csv")

In [63]:
dataset.loc[dataset['Suggested Job Role'].str.contains('Engineer', case=False), 'Suggested Job Role'] = 'Engineer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Analyst', case=False), 'Suggested Job Role'] = 'Analyst'
dataset.loc[dataset['Suggested Job Role'].str.contains('Administrator', case=False), 'Suggested Job Role'] = 'Manager'
dataset.loc[dataset['Suggested Job Role'].str.contains('Manager', case=False), 'Suggested Job Role'] = 'Manager'
dataset.loc[dataset['Suggested Job Role'].str.contains('Designer', case=False), 'Suggested Job Role'] = 'Designer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Developer', case=False), 'Suggested Job Role'] = 'Developer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Quality Assurance', case=False), 'Suggested Job Role'] = 'Technical Support'
dataset.loc[dataset['Suggested Job Role'].str.contains('Support', case=False), 'Suggested Job Role'] = 'Technical Support'
dataset.loc[dataset['Suggested Job Role'].str.contains('Architect', case=False), 'Suggested Job Role'] = 'Designer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Design & UX', case=False), 'Suggested Job Role'] = 'Designer'
dataset.loc[dataset['Suggested Job Role'].str.contains('Information Technology Auditor', case=False), 'Suggested Job Role'] = 'Manager'

In [64]:
print(dataset['Suggested Job Role'].unique())

['Developer' 'Manager' 'Analyst' 'Engineer' 'Designer' 'Technical Support']

In [65]:
dataset['Suggested Job Role'].value_counts()

Manager              5181
Analyst              3874
Developer            3394
Engineer             2973
Designer             2319
Technical Support    2259
Name: Suggested Job Role, dtype: int64

In [66]:
print(dataset.isna().sum())

Acedamic percentage in Operating Systems    0
percentage in Algorithms                    0
Percentage in Programming Concepts          0
Percentage in Software Engineering          0
Percentage in Computer Networks             0
Percentage in Electronics Subjects          0
Percentage in Computer Architecture         0
Percentage in Mathematics                   0
Percentage in Communication skills          0
Hours working per day                       0
Logical quotient rating                     0
hackathons                                  0
coding skills rating                        0
public speaking points                      0
can work long time before system?           0
self-learning capability?                   0
Extra-courses did                           0
certifications                              0
workshops                                   0
talenttests taken?                          0
olympiads                                   0
reading and writing skills                  0
memory capability score                     0
Interested subjects                         0
interested career area                      0
Job/Higher Studies?                         0
Type of company want to settle in?          0
Taken inputs from seniors or elders         0
interested in games                         0
Interested Type of Books                    0
Salary Range Expected                       0
In a Realtionship?                          0
Gentle or Tuff behaviour?                   0
Management or Technical                     0
Salary/work                                 0
hard/smart worker                           0
worked in teams ever?                       0
Introvert                                   0
Suggested Job Role                          0
dtype: int64

In [67]:
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
for column in dataset.columns[14:]:
    dataset[column] = lb_make.fit_transform(dataset[column])

In [68]:
X= dataset.iloc[:,0:38]
y= dataset.iloc[:,38]

In [69]:
#Label Encoding k lia
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

y1=encoder.fit_transform(y)
Y=pd.get_dummies(y1).values

In [70]:
from sklearn.preprocessing import StandardScaler
normalized_data = StandardScaler().fit_transform(X)
print(normalized_data.shape)
print(X)

(20000, 38)
       Acedamic percentage in Operating Systems  ...  Introvert
0                                            69  ...          0
1                                            78  ...          1
2                                            71  ...          1
3                                            76  ...          1
4                                            92  ...          1
...                                         ...  ...        ...
19995                                        83  ...          0
19996                                        80  ...          1
19997                                        83  ...          1
19998                                        68  ...          0
19999                                        73  ...          0

[20000 rows x 38 columns]

In [71]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.1,random_state=10)

In [72]:
X_train

       Acedamic percentage in Operating Systems  ...  Introvert
11182                                        69  ...          1
6239                                         85  ...          1
10576                                        68  ...          0
9324                                         60  ...          1
14919                                        74  ...          0
...                                         ...  ...        ...
9372                                         75  ...          0
7291                                         89  ...          0
17728                                        84  ...          1
7293                                         82  ...          1
17673                                        90  ...          1

[18000 rows x 38 columns]

In [73]:
model=Sequential()
model.add(Dense(38,input_shape=(38,),activation='relu'))
model.add(Dense(6,activation='softmax'))
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [74]:
model.fit(X_train,y_train, batch_size=10, epochs=30)

Epoch 1/30
1800/1800 [==============================] - 3s 2ms/step - loss: 4.5054 - accuracy: 0.1867
Epoch 2/30
1800/1800 [==============================] - 3s 2ms/step - loss: 2.0151 - accuracy: 0.1988
Epoch 3/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.9743 - accuracy: 0.2037
Epoch 4/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.9711 - accuracy: 0.2016
Epoch 5/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.9468 - accuracy: 0.2015
Epoch 6/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.9395 - accuracy: 0.2084
Epoch 7/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.9045 - accuracy: 0.2077
Epoch 8/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.9019 - accuracy: 0.2108
Epoch 9/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.8818 - accuracy: 0.2128
Epoch 10/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.8639 - accuracy: 0.2109
Epoch 11/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.8306 - accuracy: 0.2191
Epoch 12/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.8158 - accuracy: 0.2223
Epoch 13/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7831 - accuracy: 0.2393
Epoch 14/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7653 - accuracy: 0.2519
Epoch 15/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7551 - accuracy: 0.2586
Epoch 16/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7523 - accuracy: 0.2584
Epoch 17/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7505 - accuracy: 0.2598
Epoch 18/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7483 - accuracy: 0.2598
Epoch 19/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7484 - accuracy: 0.2598
Epoch 20/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 21/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 22/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 23/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7481 - accuracy: 0.2598
Epoch 24/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 25/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7481 - accuracy: 0.2598
Epoch 26/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 27/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 28/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 29/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598
Epoch 30/30
1800/1800 [==============================] - 3s 2ms/step - loss: 1.7482 - accuracy: 0.2598

In [75]:
y_pred= model.predict(X_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)

In [76]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       392
           1       0.00      0.00      0.00       248
           2       0.00      0.00      0.00       338
           3       0.00      0.00      0.00       300
           4       0.25      1.00      0.40       505
           5       0.00      0.00      0.00       217

    accuracy                           0.25      2000
   macro avg       0.04      0.17      0.07      2000
weighted avg       0.06      0.25      0.10      2000

[[  0   0   0   0 392   0]
 [  0   0   0   0 248   0]
 [  0   0   0   0 338   0]
 [  0   0   0   0 300   0]
 [  0   0   0   0 505   0]
 [  0   0   0   0 217   0]]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))